# ~/.bashrc
# terminal config file
# Adrian Juszczak
# adrian@juszczak.io
# https://git.io/juszczak

# case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob;

# append to the Bash history file, rather than overwriting it
shopt -s histappend;

# autocorrect typos in path names when using `cd`
shopt -s cdspell;

# enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
	shopt -s "$option" 2> /dev/null;
done;

# set prompt
prompt="$HOME/.bash/prompt/promptline.sh"
if [ -f $prompt ]; then
	source $prompt
fi
unset prompt;

# set completions
completions="$(brew --prefix)/etc/bash_completion"
if [ -f $completions ]; then
	source $completions
fi
unset completions;

# env vars
variables="$HOME/.bash/env/variables.sh"
if [ -f $variables ]; then
	source $variables
fi

# set completion for ssh hostnames
sshconfig="$HOME/.ssh/config"
[ -e "$sshconfig" ] && \
	complete -o "default" -o "nospace" \
	-W "$(grep "^Host" $sshconfig | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" \
	scp sftp ssh;
unset sshconfig;

# set marks
marks="$HOME/.bash/marks/marks.sh"
if [ -f $marks ]; then
	source $marks
fi
unset marks;

# set gnu ls
gls="$HOME/.bash/utils/gls.sh"
if [ -f $gls ]; then
	source $gls
fi
unset gls;

# setup nvm
nvm="$HOME/.bash/utils/nvm.sh"
if [ -f $nvm ]; then
	source $nvm
fi
unset nvm

# setup android sdk
android_sdk="$HOME/.bash/utils/android.sh"
if [ -f $android_sdk ]; then
	source $android_sdk
fi
unset android_sdk

# set vi mode
set -o vi
